name: Atualizar Contador

on:
  workflow_dispatch:  # permite execução manual
  schedule:
    - cron: "*/1 * * * *"  # a cada minuto

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Rodar script Python
        run: python atualizar_numero.py

      - name: Commitar e enviar alterações
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _data/contador.md
          git commit -m "Update contador [auto]"
          git push
